// src/components/bot-card.tsx
import { Compass, Eye, UserRoundPlus, Vote } from "lucide-react";
import approx from "approximate-number";
import getAvatarURL from "@/lib/get-avatar-url";
import { Button, buttonVariants } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import ColorThief from "colorthief";
import { useEffect, useRef, useState } from "react";
import TwemojiText from "./twemoji-text";

interface Card {
  img: string;
  msg: string;
  title: string;
}

interface Bot {
  IS_SKELETON?: boolean; //this is going to be a placeholder, remove it when you have the actual data
  card: Card;
  owners: string[] | { id: string; username: string; avatar: string }[];
  approved: boolean;
  servers: number;
  promoted: boolean;
  votes: number;
  badges: string[];
  opted_coins: boolean;
  id: string;
  username: string;
  discriminator: string;
  avatar: string;
  short: string;
  desc: string;
  prefix: string;
  lib: string;
  support: string;
  bg?: string;
  banner?: string;
  github?: string;
  website?: string;
  donate?: string;
  invite: string;
  slug?: string;
  owned: boolean;
  status: "online" | "offline" | "idle" | "dnd";
  addedAt: string;
}

export type { Bot, Card };

const colorThief = new ColorThief();

export default function BotCard({ bot, edit }: { bot: Bot; edit: Boolean }) {
  const imageRef = useRef(null);
  const [bgColor, setBgColor] = useState();
  useEffect(() => {
    if (imageRef.current) {
      //@ts-ignore
      if (imageRef.current.complete) {
        setBgColor(colorThief.getColor(imageRef.current));
      } else {
        //@ts-ignore
        imageRef.current.onload = () => {
          setBgColor(colorThief.getColor(imageRef.current));
        };
      }
    }
  }, [imageRef]);
  if (bot.bg && !bot.bg.startsWith("http"))
    bot.bg = `https://cdn.discordapp.com/banners/${bot.id}/${bot.bg}.webp?size=512`;
  return (
    <div
      className="block bg-popover rounded-lg w-96 md:max-w-80 shadow-black/90 group hover:shadow-2xl hover:-translate-y-2 animation duration-300 mb-4 border"
      style={
        bot.bg
          ? {
              backgroundImage: `url(${bot.bg})`,
              backgroundSize: "cover",
              backgroundPosition: "center",
            }
          : {
              backgroundColor: `rgb(${bgColor})`,
              backgroundSize: "cover",
              backgroundPosition: "center",
            }
      }
    >
      <div
        className="h-32 w-full rounded-t-lg"
        style={
          bot.bg
            ? {
                backgroundImage: `url(${bot.bg})`,
                backgroundSize: "cover",
                backgroundPosition: "center",
              }
            : {
                backgroundColor: `rgb(${bgColor})`,
                backgroundSize: "cover",
                backgroundPosition: "center",
              }
        }
      />
      <div className="relative">
        {bot.IS_SKELETON ? (
          <Skeleton className="w-16 h-16 rounded-full absolute top-8 left-4 shadow-black shadow-2xl bg-muted" />
        ) : (
          <>
            <img
              src={getAvatarURL(bot.id, bot.avatar, 96).replace("png","webp")}
              ref={imageRef}
              alt="avatar"
              crossOrigin="anonymous"
              width={64}
              height={64}
              loading="lazy"
              onError={async (e) => {
                //we need to send an api req to update bot's info.
                const data = await (await fetch(`/api/internals/update/bot/${bot.id}`)).json();
                if(data.success){
                  e.currentTarget.src = getAvatarURL(bot.id, data.avatar, 96).replace("png","webp");
                }
              }}
              className="z-10 w-16 h-16 rounded-full absolute -top-8 left-4 border-4 border-card bg-popover shadow-black shadow-2xl"
            />
            <span
              className={`z-10 -bottom-8 left-16 absolute w-6 h-6 ${
                bot.status == "online"
                  ? "bg-green-500"
                  : bot.status == "offline"
                  ? "bg-gray-500"
                  : bot.status == "idle"
                  ? "bg-secondary"
                  : "bg-green-500"
              } border-4 border-card rounded-full`}
            ></span>
          </>
        )}
      </div>
      <div className="pb-2 bg-popover group-hover:bg-popover/90 backdrop-blur-md animate animate-[bg] duration-300 rounded-b-md">
        <div className="mx-4 pt-12">
          {bot.IS_SKELETON ? (
            <>
              <Skeleton className="w-32 my-1 h-6" />
              <div className="flex items-center gap-1">
                <Skeleton className="w-24 my-1 h-4" />
                <Skeleton className="w-8 my-1 h-4 bg-primary" />
              </div>
            </>
          ) : (
            <div className="h-20 overflow-y-scroll">
              <h2 className="font-heading text-2xl font-semibold">
                {bot.username}
              </h2>
              <span className="relative bottom-1 text-xs text-gray-400">
                {bot.username}#{bot.discriminator}
              </span>
              <span className="relative bottom-1 ml-1 bg-primary text-white rounded-md px-1 text-xs font-heading">
                APP
              </span>
            </div>
          )}
          <div className="my-4 flex items-center">
            {bot.IS_SKELETON ? (
              <div className="flex gap-2">
                <div className="flex">
                  <Skeleton className="w-10 h-5 rounded-r-none bg-muted dark:bg-card" />
                  <Skeleton className="w-8 h-5 rounded-l-none bg-primary" />
                </div>
                <div className="flex">
                  <Skeleton className="w-12 h-5 rounded-r-none bg-muted dark:bg-card" />
                  <Skeleton className="w-6 h-5 rounded-l-none bg-green-600" />
                </div>
              </div>
            ) : (
              <>
                <Tag
                  firstClass="bg-muted dark:bg-card text-white font-sans"
                  firstChild={
                    <>
                      <Compass className="w-3 h-3 mr-1" />
                      In
                    </>
                  }
                  secondClass="bg-primary text-white"
                  secondChild={approx(bot.servers)}
                />
                <Tag
                  firstClass="bg-muted dark:bg-card text-white"
                  firstChild={
                    <>
                      <Vote className="w-4 h-4 mr-1" />
                      Votes
                    </>
                  }
                  secondClass="bg-green-600 text-white"
                  secondChild={approx(bot.votes)}
                />
              </>
            )}
          </div>
        </div>
        <div className="mx-2 bg-card pb-2 rounded-md">
          <div className="mx-2 pt-4 text-sm h-20 leading-5 overflow-y-auto rounded-md font-light">
            {bot.IS_SKELETON ? (
              <div className="flex flex-col gap-1">
                <div className="flex gap-1">
                  <Skeleton className="w-32 h-4" />{" "}
                  <Skeleton className="w-12 h-4" />
                </div>
                <div className="flex gap-1">
                  <Skeleton className="w-8 h-4" />{" "}
                  <Skeleton className="w-16 h-4" />{" "}
                  <Skeleton className="w-28 h-4" />
                </div>
                <div className="flex gap-1">
                  <Skeleton className="w-36 h-4" />{" "}
                  <Skeleton className="w-16 h-4" />
                </div>
              </div>
            ) : (
              <TwemojiText>{bot.short}</TwemojiText>
            )}
          </div>
          <div className="mt-8 mx-2 flex flex-col gap-2">
            {bot.IS_SKELETON ? (
              <>
                <Skeleton className="w-full h-9" />
                <Skeleton className="w-full h-9" />
              </>
            ) : (
              <>
                <a
                  href={`/bots/${bot.slug}`}
                  className={buttonVariants({
                    variant: "default",
                  })}
                >
                  <Eye className="w-4 h-4 mr-2" />
                  View
                </a>
                <a
                  href={`${bot.invite}`}
                  className={buttonVariants({
                    variant: "outline",
                  })}
                >
                  <UserRoundPlus className="w-4 h-4 mr-2" />
                  Invite
                </a>
                {
                  edit && (
                    <a
                      href={`/dashboard/bots/edit/${bot.id}`}
                      className={buttonVariants({
                        variant: "secondary",
                      })}
                    >
                      Edit
                    </a>
                  )
                }
              </>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

function Tag({
  firstClass,
  firstChild,
  secondClass,
  secondChild,
}: {
  firstClass: string;
  firstChild: React.ReactNode;
  secondClass: string;
  secondChild: React.ReactNode;
}) {
  return (
    <span className="flex rounded-sm text-sm font-medium text-gray-700 mr-2">
      <span className={`px-2 rounded-l-sm flex items-center ${firstClass}`}>
        {firstChild}
      </span>
      <span className={`px-2 rounded-r-sm text-center ${secondClass}`}>
        {secondChild}
      </span>
    </span>
  );
}

// src/lib/components/BotCard.svelte
<script lang="ts">
	import { Compass, ChevronUp, Eye, UserRoundPlus } from "@lucide/svelte";
	import { onMount } from "svelte";
	import getAvatarURL from "$lib/get-avatar-url";
	import approx from "$lib/approx-num";
	import Tag from "$lib/components/ui/Tag.svelte";
	import TwemojiText from "$lib/components/TwemojiText.svelte";
	import { buttonVariants } from "$lib/components/ui/button.js";

	export let bot: any;
	export let edit: boolean = false;

	let hovered = false;
	let imageRef: HTMLImageElement | null = null;
	let bgColor: number[] | null = null;

	// Overrides bot.bg after a successful refresh - keeps the card in sync
	// without requiring a full page reload or parent re-render.
	let bgOverride: string | null = null;

	// Normalize background URL (mirrors old repo logic)
	$: bgUrl = (() => {
		const raw = bgOverride ?? bot?.bg;
		if (!raw) return null;
		if (typeof raw === "string" && !raw.startsWith("http")) {
			return `https://cdn.discordapp.com/banners/${bot.id}/${raw}.webp?size=512`;
		}
		return raw as string;
	})();

	$: bgStyle = bgUrl
		? `background-image: url('${bgUrl}'); background-size: cover; background-position: center;`
		: bgColor
			? `background-color: rgb(${bgColor[0]},${bgColor[1]},${bgColor[2]}); background-size: cover; background-position: center;`
			: "";

	$: isAnimated = bot?.avatar?.startsWith("a_") ?? false;

	$: avatarSrc = (() => {
		if (!bot) return "/assets/img/bot/logo-144.png";
		if (bot.avatar === "0") return getAvatarURL(bot.id, bot.avatar);
		const base = getAvatarURL(bot.id, bot.avatar ?? "0", 96).replace(".png", ".webp");
		if (isAnimated) {
			// Always get the webp URL, then swap extension based on hover state
			const webp = base.replace(".gif", ".webp");
			return hovered ? webp.replace(".webp", ".gif") : webp;
		}
		return base;
	})();

	$: statusClass = (() => {
		if (bot?.status === "online") return "bg-green-500";
		if (bot?.status === "offline") return "bg-gray-500";
		if (bot?.status === "idle") return "bg-yellow-400";
		if (bot?.status === "dnd") return "bg-red-500";
		return "bg-green-500"; // default/unknown → show online
	})();

	onMount(async () => {
		try {
			const { default: ColorThief } = await import("colorthief");
			const CT = ColorThief as unknown as new () => {
				getColor: (img: HTMLImageElement) => number[];
			};
			const colorThief = new CT();

			function trySetColor() {
				try {
					if (imageRef) {
						const c = colorThief.getColor(imageRef);
						if (Array.isArray(c)) bgColor = c;
					}
				} catch {
					bgColor = null;
				}
			}

			if (imageRef) {
				if (imageRef.complete) trySetColor();
				else imageRef.onload = () => trySetColor();
			}
		} catch {
			// noop - ColorThief unavailable or image not ready
		}
	});

	// Guard: only dispatch one refresh per card instance to avoid flooding the
	// endpoint when both the avatar and bg images fail at the same time.
	let refreshDispatched = false;

	async function handleImageError(event: Event) {
		if (refreshDispatched) return;

		const src = (event.target as HTMLImageElement)?.src ?? "";

		// Only trigger for Discord CDN images - unrelated external image 404s
		// should not cause a bot refresh.
		const isDiscordImage =
			src.startsWith("https://cdn.discordapp.com/") ||
			src.startsWith("https://media.discordapp.net/");

		if (!isDiscordImage) return;

		const id = bot?.id;
		if (!id) return;

		refreshDispatched = true;

		try {
			// POST to the public proxy - DISCORD_TOKEN stays server-side only.
			const res = await fetch(`/api/bots/${encodeURIComponent(id)}/refresh`, {
				method: "POST",
				headers: { "Content-Type": "application/json" }
			});
			if (res.ok) {
				const data = await res.json().catch(() => null);
				// If the server resolved a fresh bg URL, apply it immediately so
				// the card re-renders with the valid image rather than staying broken.
				if (data?.newBg) {
					bgOverride = data.newBg;
				}
			}
		} catch {
			// Network errors are non-fatal; best-effort only.
		}
	}
</script>

<div
	class="block bg-popover rounded-lg w-96 md:max-w-80 shadow-black/90 group hover:shadow-2xl hover:-translate-y-2 transition-all duration-300 mb-4 border"
	style={bgStyle}
	role="presentation"
	on:mouseenter={() => (hovered = true)}
	on:mouseleave={() => (hovered = false)}
>
	<!-- Banner / header area -->
	<div class="h-32 w-full rounded-t-lg" style={bgStyle}></div>

	<!-- Avatar row -->
	<div class="relative">
		{#if bot?.IS_SKELETON}
			<div
				class="w-16 h-16 rounded-full absolute -top-8 left-4 border-4 border-card bg-muted animate-pulse shadow-black shadow-2xl"
			></div>
		{:else}
			<img
				bind:this={imageRef}
				src={avatarSrc}
				alt="avatar"
				crossorigin="anonymous"
				width="64"
				height="64"
				loading="lazy"
				on:error={handleImageError}
				class="z-10 w-16 h-16 rounded-full absolute -top-8 left-4 border-4 border-card bg-popover shadow-black shadow-2xl"
			/>
			<!-- Status indicator -->
			<span
				class="z-10 absolute left-16 -bottom-8 w-6 h-6 border-4 border-card rounded-full {statusClass}"
			></span>
		{/if}
	</div>

	<!-- Card body -->
	<div
		class="pb-2 bg-popover group-hover:bg-popover/90 backdrop-blur-md rounded-b-md transition-colors duration-300"
	>
		<div class="mx-4 pt-12">
			<!-- Bot name / discriminator -->
			{#if bot?.IS_SKELETON}
				<div class="w-32 my-1 h-6 bg-muted animate-pulse rounded"></div>
				<div class="flex items-center gap-1 mt-2">
					<div class="w-24 my-1 h-4 bg-muted animate-pulse rounded"></div>
					<div class="w-8 my-1 h-4 bg-primary/40 animate-pulse rounded"></div>
				</div>
			{:else}
				<div class="h-20 overflow-y-auto text-left">
					<h2 class="font-heading text-2xl font-semibold">{bot?.username ?? ""}</h2>
					<span class="relative bottom-1 text-xs text-gray-400">
						{bot?.username ?? ""}#{bot?.discriminator ?? "0000"}
					</span>
					<span
						class="relative bottom-1 ml-1 bg-primary text-white rounded-md px-1 text-xs font-heading"
					>
						APP
					</span>
				</div>
			{/if}

			<!-- Stats tags -->
			<div class="my-4 flex items-center">
				{#if bot?.IS_SKELETON}
					<div class="flex gap-2">
						<div class="flex">
							<div class="w-10 h-5 rounded-l-sm bg-muted animate-pulse"></div>
							<div class="w-8 h-5 rounded-r-sm bg-primary/40 animate-pulse"></div>
						</div>
						<div class="flex">
							<div class="w-12 h-5 rounded-l-sm bg-muted animate-pulse"></div>
							<div class="w-6 h-5 rounded-r-sm bg-green-600/40 animate-pulse"></div>
						</div>
					</div>
				{:else}
					<!-- Servers tag -->
					<Tag
						firstClass="bg-muted dark:bg-card text-white font-sans"
						secondClass="bg-primary text-white"
					>
						<span slot="first" class="flex items-center">
							<Compass class="w-3 h-3 mr-1" aria-hidden="true" />
							In
						</span>
						<span slot="second">{approx(bot?.servers)}</span>
					</Tag>
					<!-- Votes tag -->
					<Tag firstClass="bg-muted dark:bg-card text-white" secondClass="bg-green-600 text-white">
						<span slot="first" class="flex items-center">
							<ChevronUp class="w-4 h-4 mr-1" aria-hidden="true" />
							Votes
						</span>
						<span slot="second">{approx(bot?.votes)}</span>
					</Tag>
				{/if}
			</div>
		</div>

		<!-- Description + buttons inner card -->
		<div class="mx-2 bg-card pb-2 rounded-md">
			<!-- Short description -->
			<div class="mx-2 pt-4 text-sm h-20 leading-5 overflow-y-auto rounded-md font-light text-left">
				{#if bot?.IS_SKELETON}
					<div class="flex flex-col gap-1">
						<div class="flex gap-1">
							<div class="w-32 h-4 bg-muted animate-pulse rounded"></div>
							<div class="w-12 h-4 bg-muted animate-pulse rounded"></div>
						</div>
						<div class="flex gap-1">
							<div class="w-8 h-4 bg-muted animate-pulse rounded"></div>
							<div class="w-16 h-4 bg-muted animate-pulse rounded"></div>
							<div class="w-28 h-4 bg-muted animate-pulse rounded"></div>
						</div>
						<div class="flex gap-1">
							<div class="w-36 h-4 bg-muted animate-pulse rounded"></div>
							<div class="w-16 h-4 bg-muted animate-pulse rounded"></div>
						</div>
					</div>
				{:else}
					<TwemojiText>{bot?.short ?? ""}</TwemojiText>
				{/if}
			</div>

			<!-- Action buttons -->
			<div class="mt-8 mx-2 flex flex-col gap-2">
				{#if bot?.IS_SKELETON}
					<div class="w-full h-9 bg-muted animate-pulse rounded-md"></div>
					<div class="w-full h-9 bg-muted animate-pulse rounded-md"></div>
				{:else}
					<a href="/bots/{bot?.slug ?? bot?.id}" class={buttonVariants({ variant: "default" })}>
						<Eye class="w-4 h-4 mr-2" aria-hidden="true" />
						View
					</a>
					<a
						href={bot?.invite ?? "#"}
						target="_blank"
						rel="noopener noreferrer"
						class={buttonVariants({ variant: "outline" })}
					>
						<UserRoundPlus class="w-4 h-4 mr-2" aria-hidden="true" />
						Invite
					</a>
					{#if edit}
						<a
							href="/dashboard/bots/edit/{bot?.id}"
							class={buttonVariants({ variant: "secondary" })}
						>
							Edit
						</a>
					{/if}
				{/if}
			</div>
		</div>
	</div>
</div>
